services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      redis:
        condition: service_started
    
  redis:
    image: redis