name: Build Flask App

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  REPO_NAME: " ${{ vars.DOCKERHUB_USERNAME }}/devops-project"
    
jobs:
  build_app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login To Docker Repository
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REPO_NAME }}:latest , ${{ env.REPO_NAME }}:${{ github.sha }}

            
    